"""STL Grid Generator - Generate rectangular STL grids with optional holes."""

__version__ = "0.1.0"
__author__ = "Generated by Claude Code"

from .core import STLGridGenerator
from .geometry import CoordinateFrame
from .triangulation import triangulate_rectangle, triangulate_ring

__all__ = [
    "STLGridGenerator",
    "CoordinateFrame",
    "triangulate_rectangle",
    "triangulate_ring",
]