"""Setup configuration for STL Grid Generator."""

from setuptools import setup, find_packages
from pathlib import Path

# Read README for long description
this_directory = Path(__file__).parent
long_description = ""
readme_path = this_directory / "README.md"
if readme_path.exists():
    long_description = readme_path.read_text(encoding='utf-8')

# Read version from package
version = "0.1.0"

setup(
    name="stl-grid-generator",
    version=version,
    author="Generated by Claude Code",
    author_email="noreply@example.com",
    description="Generate rectangular STL grids with optional holes",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/example/stl-grid-generator",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Manufacturing",
        "Topic :: Scientific/Engineering :: Visualization",
        "Topic :: Multimedia :: Graphics :: 3D Modeling",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.7",
    install_requires=[
        "numpy>=1.18.0",
        "PyYAML>=5.4.0",
    ],
    extras_require={
        "earcut": ["mapbox_earcut>=1.0.0"],
        "trimesh": ["trimesh>=3.0.0", "shapely>=1.7.0"],
        "full": ["mapbox_earcut>=1.0.0", "trimesh>=3.0.0", "shapely>=1.7.0"],
        "dev": [
            "pytest>=6.0",
            "pytest-cov>=2.10",
            "black>=21.0",
            "flake8>=3.8",
            "mypy>=0.800",
        ],
    },
    entry_points={
        "console_scripts": [
            "stl-grid-gen=stl_grid_generator.cli:main",
        ],
    },
    keywords="stl mesh 3d grid generator cad manufacturing",
    project_urls={
        "Bug Reports": "https://github.com/example/stl-grid-generator/issues",
        "Source": "https://github.com/example/stl-grid-generator",
        "Documentation": "https://github.com/example/stl-grid-generator#readme",
    },
)